### ISSUE TITLE
KeyError: "None of [Index(['prompt', 'completion'], dtype='object')] are in the [columns]"

### ISSUE THREAD

**Issue by cristovamperes** [rchikhi/LLM-WhatsApp-chat-history#3]
not managed to execute. Tried multiple ways (exactly like the chat, different, with and without brackets, etc) to insert the names but none worked.
What am I doing wrong?

python convert.py ./chats/chat.txt "[me]" "[her]"

Traceback (most recent call last):
  File "/content/convert.py", line 93, in <module>
    converter(path, prompter, responder).to_json(f'output_{save_file}.json',lines=True,orient='records', force_ascii=False)
  File "/content/convert.py", line 75, in converter
    df = parse_whatsapp_text_into_dataframe(text, prompter, responder)
  File "/content/convert.py", line 54, in parse_whatsapp_text_into_dataframe
    df = pd.DataFrame.from_dict(result_dict).T[['prompt', 'completion']]
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 3813, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 6070, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 6130, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['prompt', 'completion'], dtype='object')] are in the [columns]"

**Comment by cristovamperes** [comment]
by the way, this is the pattern of the exported chat from my Whatsapp

[11/03/16 22:29:51] Her: 😘😘
‎[11/03/16 22:30:02] Her: ‎audio omitted
‎[11/03/16 22:30:41] Me: ‎audio omitted
‎[11/03/16 22:38:37] Her: ‎audio omitted
[11/03/16 22:38:56] Me: hahahahaah
[11/03/16 23:16:40] Me: hello??
[11/03/16 23:16:55] Me: trying to call you
‎[11/03/16 23:16:56] Her: ‎audio omitted
[11/03/16 23:17:03] Me: ok

**Comment by cristovamperes** [comment]
It worked. I had to remove the [APM]{2} part because my file is not using AM/PM information

**Comment by spookyuser** [comment]
Same, except for me it was that my dates were YYYY-MM-DD which i guess comes from the locale of your phone
